--table schemas
DROP TABLE IF EXISTS blocks;
DROP TABLE IF EXISTS flats;
DROP TABLE IF EXISTS tenants;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS fees;

CREATE TABLE blocks
(
    id INT GENERATED BY DEFAULT AS PRIMARY KEY,
    name VARCHAR(10) NOT NULL
);

CREATE TABLE flats
(
    id INT GENERATED BY DEFAULT AS PRIMARY KEY,
    flat_number INT NOT NULL,
    block_name VARCHAR(10) NOT NULL,
    debt INT DEFAULT 0,
    payment INT NOT NULL,
    FOREIGN KEY(block_name) REFERENCES blocks(name)

);

CREATE TABLE payments
(
    id INT GENERATED BY DEFAULT AS PRIMARY KEY,
    block_name VARCHAR(10) NOT NULL,
    flat_number INT NOT NULL,
    total_fee INT NOT NULL,
    payment_date DATE NOT NULL,
    payment_amount INT NOT NULL,
    FOREIGN KEY(payment_amount) REFERENCES flats(payment),
    FOREIGN KEY(block_name) REFERENCES blocks(name),
    FOREIGN KEY(flat_number) REFERENCES flats(flat_number),
    FOREIGN KEY(total_fee) REFERENCES fees(total_fee),

);

CREATE TABLE fees
(
    id INT GENERATED BY DEFAULT AS PRIMARY KEY,
    electricity_bill INT DEFAULT 0,
    gas_bill INT DEFAULT 0,
    water_bill INT DEFAULT 0,
    dues INT DEFAULT 0,
    total_fee INT NOT NULL,
    receivable INT DEFAULT 0,
    flat_debt INT DEFAULT 0,
    FOREIGN KEY(flat_debt) REFERENCES flats(debt)
);

CREATE TABLE tenants
(
    id INT GENERATED BY DEFAULT AS PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    block_id INT NOT NULL,
    flat_id INT NOT NULL,
    personal_payment INT DEFAULT 0,
    debt INT DEFAULT 0,
    FOREIGN KEY(block_id) REFERENCES blocks(id),
    FOREIGN KEY(flat_id) REFERENCES flats(id),
    FOREIGN KEY(debt) REFERENCES flats(debt)
);